### ISSUE TITLE
Deployment Example Error

### ISSUE THREAD

**Issue by gfleetwood** [rstudio/py-shinylive#11]
I'm using Ubuntu 20.04 and Python 3.8.10.

On Shiny For Python's site (https://shiny.rstudio.com/py/docs/shinylive.html#deploying-shinylive-applications) there is an example for deploying shinylive apps:

```
shiny create myapp
shiny static myapp site
```

The second line of code throws an error:

```
$ shiny static myapp site
Creating directory /home/gordon/.cache/shiny/shinylive
Traceback (most recent call last):
  File "/home/gordon/.local/bin/shiny", line 8, in <module>
    sys.exit(main())
  File "/home/gordon/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/gordon/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/gordon/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gordon/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gordon/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/gordon/.local/lib/python3.8/site-packages/shiny/_main.py", line 393, in static
    _static.deploy_static(
  File "/home/gordon/.local/lib/python3.8/site-packages/shiny/_static.py", line 55, in deploy_static
    shinylive_bundle_dir = _ensure_shinylive_local(version=version)
  File "/home/gordon/.local/lib/python3.8/site-packages/shiny/_static.py", line 270, in _ensure_shinylive_local
    destdir.mkdir()
  File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/gordon/.cache/shiny/shinylive'
```

**Comment by wch** [comment]
This is the same as https://github.com/rstudio/py-shiny/issues/281, which is already fixed in 0.2.3 and is on PyPI. Update with:

```
pip install --upgrade shiny
```
